<../../../mkconfig

TARG=\
	icurses.dis\
	theme.dis\
	screen.dis\
	button.dis\
	dialog.dis\
	text.dis\

MODULES=\

SYSMODULES=\
	icurses/icurses.m\
	icurses/theme.m\
	icurses/screen.m\
	icurses/button.m\
	icurses/dialog.m\
	icurses/text.m\

DISBIN=$ROOT/dis/lib/icurses

<$ROOT/mkfiles/mkdis

LIMBOFLAGS= -c $LIMBOFLAGS